// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeNumberSrvApi.Models;

namespace PrimeNumberSrvApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201112092238_DbInit")]
    partial class DbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("PrimeNumberSrvApi.Models.PrimeNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrimeValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PrimeNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
